// @generated
// This file is @generated by prost-build.
/// AbstractAccount is a smart contract that is capable of initiating txs.
///
/// This account type is similar to BaseAccount except for it doesn't have a
/// pubkey. If a pubkey is needed, it creates and returns a new NilPubKey.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AbstractAccount {
    #[prost(string, tag = "1")]
    pub address: ::prost::alloc::string::String,
    #[prost(uint64, tag = "2")]
    pub account_number: u64,
    #[prost(uint64, tag = "3")]
    pub sequence: u64,
}
impl ::prost::Name for AbstractAccount {
    const NAME: &'static str = "AbstractAccount";
    const PACKAGE: &'static str = "abstractaccount.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "abstractaccount.v1.AbstractAccount".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/abstractaccount.v1.AbstractAccount".into()
    }
}
/// NilPubKey is the pubkey type of the AbstractAccount. Basically, it represents
/// a pubkey that doesn't exist.
///
/// The actual pubkey of an AbstractAccount (if it has one) is to be stored
/// inside the contract, not at the SDK level. Signature verification is also
/// done inside the contract, typically in the BeforeTx hook.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NilPubKey {
    #[prost(bytes = "vec", tag = "1")]
    pub address_bytes: ::prost::alloc::vec::Vec<u8>,
}
impl ::prost::Name for NilPubKey {
    const NAME: &'static str = "NilPubKey";
    const PACKAGE: &'static str = "abstractaccount.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "abstractaccount.v1.NilPubKey".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/abstractaccount.v1.NilPubKey".into()
    }
}
/// EventAccountRegistered is emitted when an AbstractAccount is registered.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EventAccountRegistered {
    #[prost(string, tag = "1")]
    pub creator: ::prost::alloc::string::String,
    #[prost(uint64, tag = "2")]
    pub code_id: u64,
    #[prost(string, tag = "3")]
    pub contract_addr: ::prost::alloc::string::String,
    #[prost(uint64, tag = "4")]
    pub account_number: u64,
}
impl ::prost::Name for EventAccountRegistered {
    const NAME: &'static str = "EventAccountRegistered";
    const PACKAGE: &'static str = "abstractaccount.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "abstractaccount.v1.EventAccountRegistered".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/abstractaccount.v1.EventAccountRegistered".into()
    }
}
/// Params defines the parameters for the abstractaccount module.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Params {
    /// AllowAllCodeIDs determines whether a Wasm code ID can be used to register
    /// AbstractAccounts:
    /// - if set to true, any code ID can be used;
    /// - if set to false, only code IDs whitelisted in the AllowedCodeIDs list can
    /// be used.
    #[prost(bool, tag = "1")]
    pub allow_all_code_ids: bool,
    /// AllowedCodeIDs is the whitelist of Wasm code IDs that can be used to
    /// regiseter AbstractAccounts.
    #[prost(uint64, repeated, packed = "false", tag = "2")]
    pub allowed_code_ids: ::prost::alloc::vec::Vec<u64>,
    /// MaxGasBefore is the maximum amount of gas that can be consumed by the
    /// contract call in the before_tx decorator.
    ///
    /// Must be greater than zero.
    #[prost(uint64, tag = "3")]
    pub max_gas_before: u64,
    /// MaxGasAfter is the maximum amount of gas that can be consumed by the
    /// contract call in the after_tx decorator.
    ///
    /// Must be greater than zero.
    #[prost(uint64, tag = "4")]
    pub max_gas_after: u64,
}
impl ::prost::Name for Params {
    const NAME: &'static str = "Params";
    const PACKAGE: &'static str = "abstractaccount.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "abstractaccount.v1.Params".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/abstractaccount.v1.Params".into()
    }
}
/// GenesisState defines the genesis state of the abstractaccount module.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GenesisState {
    #[prost(message, optional, tag = "1")]
    pub params: ::core::option::Option<Params>,
    #[prost(uint64, tag = "2")]
    pub next_account_id: u64,
}
impl ::prost::Name for GenesisState {
    const NAME: &'static str = "GenesisState";
    const PACKAGE: &'static str = "abstractaccount.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "abstractaccount.v1.GenesisState".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/abstractaccount.v1.GenesisState".into()
    }
}
// ---------------------------------- Params -----------------------------------

/// QueryParamsRequest is the request type for the Query/Params RPC method.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct QueryParamsRequest {}
impl ::prost::Name for QueryParamsRequest {
    const NAME: &'static str = "QueryParamsRequest";
    const PACKAGE: &'static str = "abstractaccount.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "abstractaccount.v1.QueryParamsRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/abstractaccount.v1.QueryParamsRequest".into()
    }
}
/// QueryParamsResponse is the response type for the Query/Params RPC method.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct QueryParamsResponse {
    #[prost(message, optional, tag = "1")]
    pub params: ::core::option::Option<Params>,
}
impl ::prost::Name for QueryParamsResponse {
    const NAME: &'static str = "QueryParamsResponse";
    const PACKAGE: &'static str = "abstractaccount.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "abstractaccount.v1.QueryParamsResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/abstractaccount.v1.QueryParamsResponse".into()
    }
}
// ------------------------------- UpdateParams --------------------------------

/// MsgUpdateParams is the message for updating the module parameters.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MsgUpdateParams {
    #[prost(string, tag = "1")]
    pub sender: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub params: ::core::option::Option<Params>,
}
impl ::prost::Name for MsgUpdateParams {
    const NAME: &'static str = "MsgUpdateParams";
    const PACKAGE: &'static str = "abstractaccount.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "abstractaccount.v1.MsgUpdateParams".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/abstractaccount.v1.MsgUpdateParams".into()
    }
}
/// MsgUpdateParamsResponse is the response message for MsgUpdateParams.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct MsgUpdateParamsResponse {}
impl ::prost::Name for MsgUpdateParamsResponse {
    const NAME: &'static str = "MsgUpdateParamsResponse";
    const PACKAGE: &'static str = "abstractaccount.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "abstractaccount.v1.MsgUpdateParamsResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/abstractaccount.v1.MsgUpdateParamsResponse".into()
    }
}
// ------------------------------ RegisterAccount ------------------------------

/// MsgRegisterAccount is the message for registering a new AbstractAccount.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MsgRegisterAccount {
    /// Sender is the actor who signs the message
    #[prost(string, tag = "1")]
    pub sender: ::prost::alloc::string::String,
    /// CodeID indicates which wasm binary code is to be used for this contract
    #[prost(uint64, tag = "2")]
    pub code_id: u64,
    /// Msg is the JSON-encoded instantiate message for the contract
    #[prost(bytes = "vec", tag = "3")]
    pub msg: ::prost::alloc::vec::Vec<u8>,
    /// Funds are coins to be deposited to the contract on instantiattion
    #[prost(message, repeated, tag = "4")]
    pub funds: ::prost::alloc::vec::Vec<crate::cosmos::base::v1beta1::Coin>,
    /// Salt is an arbinary value to be used in deriving the account address.
    /// Max 64 bytes.
    #[prost(bytes = "vec", tag = "5")]
    pub salt: ::prost::alloc::vec::Vec<u8>,
}
impl ::prost::Name for MsgRegisterAccount {
    const NAME: &'static str = "MsgRegisterAccount";
    const PACKAGE: &'static str = "abstractaccount.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "abstractaccount.v1.MsgRegisterAccount".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/abstractaccount.v1.MsgRegisterAccount".into()
    }
}
/// MsgRegisterAccountResponse is the response message for MsgRegisterAccount.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MsgRegisterAccountResponse {
    #[prost(string, tag = "1")]
    pub address: ::prost::alloc::string::String,
    #[prost(bytes = "vec", tag = "2")]
    pub data: ::prost::alloc::vec::Vec<u8>,
}
impl ::prost::Name for MsgRegisterAccountResponse {
    const NAME: &'static str = "MsgRegisterAccountResponse";
    const PACKAGE: &'static str = "abstractaccount.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "abstractaccount.v1.MsgRegisterAccountResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/abstractaccount.v1.MsgRegisterAccountResponse".into()
    }
}
include!("abstractaccount.v1.serde.rs");
include!("abstractaccount.v1.tonic.rs");
// @@protoc_insertion_point(module)
